---
title: "MPG Analysis Shiny Application"
author: "Deepthi V"
date: "03 January 2026"
output: ioslides_presentation
---



## Coursera Reproducible Pitch


## MPG Analysis Shiny App

This Shiny application allows users to explore the relationship between
different automobile characteristics and miles per gallon (MPG)
using the mtcars dataset.


## Motivation

- Fuel efficiency is an important factor in automobile performance
- MPG varies with vehicle weight, engine size, and transmission
- This app provides an interactive way to understand these relationships


---

## mtcars Dataset

### Motor Trend Car Road Tests

> The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).
### Source
> Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391-411.
```{r}
library(datasets)
head(mtcars, 3)
```
---

## mtcars Dataset - Format

**A data frame with 32 observations on 11 variables.**

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

---

## Analysis - Main Code

```r
  formulaTextPoint <- reactive({
    paste("mpg ~", "as.integer(", input$variable, ")")  })
  
  fit <- reactive({
    lm(as.formula(formulaTextPoint()), data=mpgData)  })
  ...
  output$fit <- renderPrint({
    summary(fit()) })
  
  output$mpgPlot <- renderPlot({
    with(mpgData, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })  })
```

## Application Features

- Users can select different car variables
- Reactive boxplots and regression models are displayed
- Results update instantly based on user input

## Conclusion

- A simple and interactive MPG exploration tool
- Demonstrates reactive programming using Shiny
- Suitable for novice users and quick data exploration


### See the Regression Models Course Project  

- URL: *https://github.com/deepthiv16/Developing-Data-Products-Week-4-Course-Project.git*
- Find here all the data that have been use for this presentation and also for the first part of the data Science Project: "First, you will create a Shiny application and deploy it on Rstudio's servers.Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application."
